"""...

Revision ID: 1a9299fcd98c
Revises: 524386f01268
Create Date: 2026-07-03 15:42:25.307318
"""

from alembic import op
import sqlalchemy as sa

revision = '1a9299fcd98c'
down_revision = '524386f01268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###