"""Create roads table

Revision ID: 82d3c81a81ee
Revises: 44b979adbab1
Create Date: 2026-07-04 09:52:12.309335
"""

from alembic import op
import sqlalchemy as sa

revision = '82d3c81a81ee'
down_revision = '44b979adbab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roads',
    sa.Column('road_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=30), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('travel_time', sa.Integer(), nullable=False),
    sa.Column('traffic_factor', sa.Float(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roads'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roads')
    # ### end Alembic commands ###